# ![](https://ga-dash.s3.amazonaws.com/production/assets/logo-9f88ae6c9c3871690e33280fcf557f33.png) Linear algebra: review of basic concepts with numpy

Week 7| Lesson 2.2

### LEARNING OBJECTIVES
*After this lesson, you will be able to:*
- Recognize key concepts in linear algebra
- Add and calculate dot products of vectors and matrices in numpy


In [2]:
import numpy as np

## Contents
#### Vectors and matrices
#### Vector addition, scalar multiplication, dot products
#### Matrix multiplication
#### Identity matrix
#### Linear algebra operations in numpy
#### Independent practice

### Vectors and matrices

An m x n **matrix** is a rectangular array of numbers with m rows and n columns. Each number in the matrix is an entry.

$$A= \left[ \begin{array}{c}
a_{11} & a_{12} & ... & a_{1n}  \\
a_{21} & a_{22} & ... & a_{2n}  \\
... & ... & ... & ... \\
a_{m1} & a_{m2} & ... & a_{mn}
\end{array} \right]$$

$$A \in \mathbb{R}^{mn}$$

Entries can be denoted $a_{mn}$

(Definitions from 'Linear Algebra', Heffernon)

We can **decompose** matrices by factorizing them into a product of other matrices.

Matrices can have a different number of rows and columns. When they have the same number of rows and columns, they are called **square matrices**.

The **trace** of a square matrix is the sum of the elements on its top-left to lower-right diagonal:

$$\operatorname{tr}(A) = a_{11} + a_{22} + \dots + a_{nn}=\sum_{i=1}^{n} a_{ii}$$

A (column) **vector** is a matrix with a single column. Entries are components.

$$\vec{v} = \left[ \begin{array}{c}
1 \\
3 \\
7 \\
\vdots \\
n
\end{array} \right]$$

$\vec{v} \in \mathbb{R}^{n}$, where $\mathbb{R}^{n}$ is n-dimensional real coordinate space. It includes all possible real-valued n-tuples, i.e. $\vec{v}$.


Components are denoted $v_{i}$.

![](./assets/images/r3_vectors.png)

We can represent vectors as arrows in n-dimensional space, having magnitude and direction.

(Image from: 
Louis Scharf, Linear Algebra: Vectors. OpenStax CNX. Sep 17, 2009 http://cnx.org/contents/3d05d982-e21c-4f8a-ab5a-d3e94186f924@6.)

A matrix with a single row is a row vector.

$$\vec{u} = \left[ \begin{array}{c}
1&3&7
\end{array} \right]$$

It is the **transpose** of a column vector: $\vec{v}^{T} = \vec{u}$. And vice versa.

The **magnitude** of a vector $\vec{v} \in \mathbb{R}^{n}$ in is interpretable as its length, and calculable via the Euclidean distance:

$\vec{v} = \left[ \begin{array}{c}
v_{1} \\
v_{2} \\
\vdots \\
v_{n}
\end{array} \right]$

then $\| \vec{v} \| = \sqrt{v_{1}^{2} + v_{2}^{2} + ... + v_{n}^{2}}$

E.g. if $\vec{v} = 
\left[ \begin{array}{c}
3 \\
4
\end{array} \right]$, then $\| \vec{v} \| = \sqrt{3^{2} + 4^{2}}$

This is also called the vector **norm**.

Vector **addition** is straightforward. If two vectors are of equal dimensions:

$\vec{v} = \left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right],  \vec{w} = \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right]$

$\vec{v} + \vec{w} =
\left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right] + \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right] = 
\left[ \begin{array}{c}
1+1 \\
3+0 \\
7+1
\end{array} \right] = 
\left[ \begin{array}{c}
2 \\
3 \\
8
\end{array} \right]
$

(Subtraction is similar.)

![](./assets/images/r3_vectors.png)

> Check: what operations are shown here?

We scale a vector with **scalar multiplication**, multiplying a vector by a scalar (single quantity):

$ b \left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right] = 
 \left[ \begin{array}{c}
b1 \\
b3 \\
b7
\end{array} \right]$

If $\vec{a} = \left[ \begin{array}{c}
2 \\
1 
\end{array} \right]$ and $b = 3$:

![](./assets/images/scalar_multiplication_3a.png)

In [3]:
# Independent practice
# First calculate by hand, then fill in ___s to calculate with numpy.

v = np.array([3.0,4.0])
u = np.array([2.0,1.0])
print v+u           # Find sum of vectors v and u
print v-u           # Find vectors u subtracted from v
print v*3          # Find v multiplied times some scalar, e.g. 3
np.linalg.norm(v) # Find magnitude of vector v


[ 5.  5.]
[ 1.  3.]
[  9.  12.]


5.0

The **dot product** of two _n_-dimensional vectors is:

$ \vec{v} \cdot \vec{w} =\sum _{i=1}^{n}v_{i}w_{i}=v_{1}w_{1}+v_{2}w_{2}+\cdots +v_{n}w_{n} $

So, if:

$\vec{v} = \left[ \begin{array}{c}
1 \\
3 \\
7
\end{array} \right], \vec{w} = \left[ \begin{array}{c}
1 \\
0 \\
1
\end{array} \right]$

$ \vec{v} \cdot \vec{w} = 1*1 + 3*0 + 7*1 = 8 $

**Matrix multiplication**, $A_{mn} * B_{ij}$, is valid when the left matrix has the same number of columns as the right matrix has rows ($n = i$). Each entry is the dot product of corresponding row and column vectors.

![](./assets/images/matrix-multiply-a.gif)
(Image: mathisfun.com!)

The **identity matrix**, $I_{n}$ is the matrix where $I_{n} A = A$:

$$ I * \left[ \begin{array}{c}
a_{11} & a_{12} \\
a_{21} & a_{22} 
\end{array} \right] = \left[ \begin{array}{c}
a_{11} & a_{12} \\
a_{21} & a_{22} 
\end{array} \right]$$

E.g.:

$$ \left[ \begin{array}{c}
1 & 0 \\
0 & 1 
\end{array} \right] * \left[ \begin{array}{c}
3 & 4 \\
5 & 6 
\end{array} \right] = \left[ \begin{array}{c}
(1* 3 + 0 * 5) & (1 * 4 + 0 * 6) \\
(0 * 3 + 1 * 5) & (0 * 4 + 1 * 6) 
\end{array} \right] =
\left[ \begin{array}{c}
3 & 4 \\
5 & 6 
\end{array} \right]$$

This is the matrix equivalent of multiplying a value times the identity 1.

In [9]:
# Independent practice
# First calculate by hand, then fill in ___s to calculate with numpy.

A = np.array([[1, 2, 3], [4, 5, 6]]) # Create 2 x 3 matrix A, of type array
B = np.array([[1, 2], [3, 4], [5,6]]) # Create 3 x 2 matrix B, of type array
print np.dot(A,B) # Calculate A x B

A = np.arange(1,7).reshape(2,3) # Equivalently
B = np.arange(1,7).reshape(3,2)
print np.dot(A,B)

[[22 28]
 [49 64]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


## Independent practice

Review the numpy operations, and try out their examples, here: http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

This week we will work heavily with eigenvectors and eigenvalues (to be covered).

### Supplemental resources

+ For a surprisingly comprehensive (yet dense!) review, be sure to check out [Linear algebra in four pages](http://www-bcf.usc.edu/~lototsky/MATH408/LinAlg1.pdf)
+ This [deck](http://cseweb.ucsd.edu/classes/wi05/cse252a/linear_algebra_review.pdf) provides great insight into linear operations and advanced geometric topics
+ Stanford's Review and Reference [26-page](http://cs229.stanford.edu/section/cs229-linalg.pdf) guide provides a nice review
+ Spend some time on [Khan Academy](https://www.khanacademy.org/math/linear-algebra/matrix-transformations#concept-intro)!